# Generated by Django 5.1.4 on 2025-01-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="email",
            field=models.EmailField(default="default@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.table",
            ),
        ),
    ]
