# Generated by Django 5.1.4 on 2025-01-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_reservation_email_reservation_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("confirmed", "Подтверждено"),
                    ("rejected", "Отклонено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
