# Generated by Django 5.1.4 on 2025-01-17 09:36

import django.db.models.deletion
import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_reservation_status"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(verbose_name="Дата бронирования"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(
                default="default@example.com", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guests",
            field=models.IntegerField(
                validators=[reservations.models.validate_positive_guests],
                verbose_name="Количество гостей",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("confirmed", "Подтверждено"),
                    ("rejected", "Отклонено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.table",
                verbose_name="Столик",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.TimeField(verbose_name="Время бронирования"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["date", "time"], name="reservation_date_295b7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="reservation_status_f1a03a_idx"),
        ),
    ]
