# Generated by Django 5.1.4 on 2025-01-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateTimeField(verbose_name="Дата и время бронирования"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(max_length=100, verbose_name="Имя гостя"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guests_count",
            field=models.IntegerField(verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tables.table",
                verbose_name="Столик",
            ),
        ),
    ]
